INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (1, 'Darabont', 'Frank', 'France');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (2, 'Ford Coppola', 'Francis', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (3, 'Nolan', 'Christopher', 'UK');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (4, 'Spielberg', 'Steven', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (5, 'Tarantino', 'Quentin', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (6, 'Lumet', 'Sidney', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (7, 'Jackson', 'Peter', 'New Zealand');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (8, 'Leone', 'Sergio', 'Italy');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (9, 'Fincher', 'David', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (10, 'Kershner', 'Irvin', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (11, 'Zemeckis', 'Robert', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (12, 'Forman', 'Milos', 'Czech Republic');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (13, 'Scorsese', 'Martin', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (15, 'Wachowski', 'Lilly', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (16, 'Kurosawa', 'Akira', 'Japan');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (17, 'Lucas', 'George', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (18, 'Meirelles', 'Fernando', 'Brazil');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (19, 'Demme', 'Jonathan', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (20, 'Carpa', 'Frank', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (21, 'Singer', 'Bryan', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (22, 'Benigni', 'Roberto', 'Italy');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (23, 'Besson', 'Luc', 'France');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (24, 'Miyazaki', 'Hayao', 'Japan');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (25, 'Curtiz', 'Michael', 'Hungary');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (26, 'Kaye', 'Tony', 'UK');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (27, 'Chaplin', 'Charles', 'UK');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (28, 'Hitchcock', 'Alfred', 'UK');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (29, 'Nakache', 'Olivier', 'France');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (30, 'Cameron', 'James', 'Canada');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (31, 'Polanski', 'Roman', 'France');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (32, 'Chazelle', 'Damien', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (33, 'Scott', 'Ridley', 'UK');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (34, 'Kubrick', 'Stanley', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (35, 'Wilder', 'Billy', 'Poland');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (36, 'Allers', 'Rogers', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (37, 'von Donnersmarck', 'Florian Henckel', 'Germany');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (38, 'Tornatore', 'Giuseppe', 'Italy');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (39, 'Takahata', 'Isao', 'Japan');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (40, 'Stanton', 'Andrew', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (14, 'Wachowski', 'Lana', 'USA');
INSERT INTO project.director (directorid, lastname, firstname, country) VALUES (41, 'Soderbergh', 'Steven', 'USA');