INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (1, 'The Shawshank Redemption', '1994-10-14', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (2, 'The Godfather', '1972-03-24', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (3, 'The Godfather: Part II', '1974-12-20', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (4, 'The Dark Knight', '2008-07-18', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (5, 'Schindler''s List', '1994-02-04', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (6, 'Pulp Fiction', '1994-10-14', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (7, '12 Angry Men', '1957-04-01', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (8, 'The Lord of the Rings: The Return of the King', '2003-12-17', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (9, 'The Good, the Bad and the Ugly', '1966-12-23', 'Italy', 'English', true);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (10, 'Fight Club', '1999-10-15', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (11, 'The Lord of the Rings: The Fellowship of the Ring', '2001-12-19', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (12, 'Star Wars: Episode V - The Empire Strikes Back', '1980-06-20', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (13, 'Forrest Gump', '1994-07-06', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (14, 'Inception', '2010-07-16', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (15, 'The Lord of the Rings: The Two Towers', '2002-12-18', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (16, 'One Flew Over the Cuckoo''s Nest', '1974-11-24', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (17, 'Goodfellas', '1990-09-21', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (18, 'The Matrix', '1999-03-31', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (19, 'Seven Samurai', '1954-04-26', 'Japan', 'Japanese', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (20, 'Star Wars Episode IV - A New Hope', '1977-05-25', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (21, 'City of God', '2002-08-30', 'Brazil', 'Portuguese', true);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (22, 'Se7en', '1995-09-22', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (23, 'The Silence of the Lambs', '1991-02-14', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (24, 'It''s a Wonderful life', '1947-01-07', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (25, 'The Usual Suspects', '1995-09-15', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (26, 'Life is Beautiful', '1997-12-20', 'Italy', 'Italian', true);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (27, 'Leon: The Professional', '1994-11-18', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (28, 'Once Upon a Time in the West', '1968-09-21', 'Italy', 'Italian', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (29, 'Spirited Away', '2001-07-20', 'Japan', 'Japanese', true);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (30, 'Saving Private Ryan', '1998-07-24', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (31, 'Interstellar', '2014-11-07', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (32, 'Casablanca', '1943-01-23', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (33, 'American History X', '1998-11-20', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (34, 'City Lights', '1931-03-07', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (35, 'Psycho', '1960-09-08', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (36, 'Raiders of the Lost Ark', '1981-06-12', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (37, 'Rear Window', '1954-08-01', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (38, 'The Intouchables', '2011-11-02', 'France', 'French', true);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (41, 'Ocean''s Eleven', '2001-12-07', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (42, 'Inglorious Basterds', '2009-08-21', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (40, 'The Green Mile', '1999-12-10', 'USA', 'English', false);
INSERT INTO project.movie (movieid, name, datereleased, countryreleased, language, subtitles) VALUES (39, 'Modern Times', '1936-02-25', 'USA', 'English', false);