INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (1, 'Andy Dufresne', 1, 1);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (2, 'Ellie Boyd', 2, 1);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (3, 'Warden Norton', 3, 1);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (4, 'Vito Corleone', 4, 2);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (5, 'Michael Corleone', 5, 2);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (6, 'Sonny Corleone', 6, 2);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (10, 'Vito Corleone', 7, 3);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (11, 'Tom Hagen', 8, 3);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (7, 'Bruce Wayne', 9, 4);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (8, 'Joker', 10, 4);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (9, 'Harvey Dent', 11, 4);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (12, 'Oskar Schindler', 12, 5);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (14, 'Amon Goeth', 13, 5);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (109, 'Danny Ocean', 98, 41);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (13, 'Itzhak Stern', 14, 5);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (15, 'Juror 1', 17, 7);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (16, 'Juror 3', 16, 7);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (17, 'Juror 8', 15, 7);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (18, 'Vincent Vega', 18, 6);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (19, 'Jules Winnfield', 20, 6);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (20, 'Mia Wallace', 19, 6);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (21, 'Frodo', 21, 8);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (22, 'Aragorn', 22, 8);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (23, 'Gandalf', 23, 8);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (24, 'Blondie', 24, 9);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (25, 'Tuco', 25, 9);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (26, 'Sentenza/Angel Eyes', 26, 9);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (27, 'Tyler Durden', 27, 10);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (28, 'The Narrator', 28, 10);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (29, 'Robert ''Bob'' Paulsen', 29, 10);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (30, 'Legolas', 30, 11);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (31, 'Luke Skywalker', 31, 11);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (32, 'Han Solo', 32, 12);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (33, 'Princess Leia', 33, 12);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (34, 'Forrest Gump', 34, 13);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (35, 'Jenny Curran', 35, 13);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (36, 'Dan Taylor', 36, 13);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (37, 'Cobb', 37, 14);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (38, 'Arthur', 38, 14);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (39, 'Ariadne', 39, 14);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (40, 'R.P. McMurphy', 40, 16);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (41, 'Nurse Ratched', 41, 16);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (42, 'Ellis', 42, 16);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (44, 'Henry Hill', 43, 17);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (45, 'Tommy DeVito', 44, 17);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (46, 'Neo', 45, 18);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (47, 'Morpheus', 46, 18);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (48, 'Trinity', 47, 18);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (49, 'Kikuchiyo', 48, 19);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (50, 'Kambei Shimada', 49, 19);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (51, 'Shino', 50, 19);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (52, 'Buscape - Rocket', 51, 21);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (53, 'Sandro Cenoura', 52, 21);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (54, 'Ze Pequeno - Li''l Ze', 53, 21);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (57, 'John Doe', 54, 22);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (58, 'Clarice Starling', 55, 23);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (59, 'Dr. Hannibal Lecter', 56, 23);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (60, 'George Bailey', 57, 24);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (61, 'Mary Hatch', 58, 24);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (62, 'Mr. Potter', 59, 24);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (64, 'Keaton', 60, 25);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (65, 'Dave Kujan', 61, 25);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (66, 'Guido', 62, 26);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (67, 'Dora', 63, 26);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (68, 'Joshua', 64, 26);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (69, 'Leon', 65, 27);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (70, 'Stansfield', 66, 27);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (71, 'Mathilda', 67, 27);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (73, 'Harmonica', 68, 28);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (74, 'Jill McBain', 69, 28);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (75, 'Chichiro', 70, 29);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (76, 'Yubaba / Zeniba', 71, 29);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (79, 'Sergeant Horvath', 74, 30);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (80, 'Private Ryan', 73, 30);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (81, 'Cooper', 75, 31);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (82, 'Brand', 76, 31);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (83, 'Murph', 77, 31);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (84, 'Rick Blaine', 78, 32);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (85, 'Ilsa Lund', 79, 32);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (86, 'Victor Laszlo', 80, 32);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (88, 'Danny Vinyard', 81, 33);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (89, 'Doris Vinyard', 82, 33);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (90, 'A Blind Girl', 84, 34);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (91, 'A Tramp', 83, 34);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (92, 'Norman Bates', 85, 35);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (93, 'Lila Crane', 87, 35);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (94, 'Marion Crane', 86, 35);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (96, 'Marion Ravenwood', 88, 36);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (97, 'Dr. Rene Belloq', 89, 36);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (99, 'Lisa Carol Fremont', 90, 37);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (100, 'Thomas J. Doyle', 91, 37);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (101, 'Driss', 93, 38);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (102, 'Philippe', 92, 38);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (104, 'A Gamin', 94, 39);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (105, 'Cafe Proprietor', 95, 39);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (107, 'John Coffey', 96, 40);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (77, 'Haku', 72, 29);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (110, 'Tess Ocean', 99, 41);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (114, 'Sgt. Donny Donowitz', 101, 42);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (43, 'James Conway', 7, 17);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (55, 'Somerset', 2, 22);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (56, 'Mills', 27, 22);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (63, 'Verbal', 54, 22);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (72, 'Frank', 15, 28);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (78, 'Captain Miller', 34, 30);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (87, 'Derek Vinyard', 28, 33);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (95, 'Indy', 80, 32);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (103, 'A Factory Worker', 83, 39);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (106, 'Paul Edgecomb', 34, 40);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (98, 'L.B. ''Jeff'' Jefferies', 57, 37);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (108, 'Brutus ''Brutal'' Howell', 97, 40);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (111, 'Rusty Ryan', 27, 41);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (112, 'Lt. Aldo Raine', 27, 42);
INSERT INTO project.role (roleid, name, actorid, movieid) VALUES (113, 'Bridget von Hammersmark', 100, 42);