INSERT INTO project.studio (studioid, name, country) VALUES (1, '20th Century Fox', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (2, 'Columbia Pictures', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (3, 'Metro-Goldwyn-Mayer', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (4, 'Paramount Pictures', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (5, 'RKO Pictures', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (6, 'United Artists', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (7, 'Universal Studios', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (8, 'Warner Bros.', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (9, 'Dimension Films', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (37, 'Pixar', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (10, 'Lionsgate Films', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (11, 'New Line Cinema', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (12, 'Miramax', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (13, 'Legendary Entertainment', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (14, 'Lucasfilm', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (15, 'Studio Ghibli', 'Japan');
INSERT INTO project.studio (studioid, name, country) VALUES (16, 'Sony Pictures', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (17, 'Toei Company', 'Japan');
INSERT INTO project.studio (studioid, name, country) VALUES (18, 'Walt Disney Pictures', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (19, 'Hollywood Pictures', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (20, 'Walt Disney Animation Studios', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (21, 'Marvel Studios', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (22, 'Nova Film', 'Netherlands');
INSERT INTO project.studio (studioid, name, country) VALUES (23, 'O2 Filmes', 'Brazil');
INSERT INTO project.studio (studioid, name, country) VALUES (24, 'Orion Studios', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (25, 'Melampo Cinematografica', 'Italy');
INSERT INTO project.studio (studioid, name, country) VALUES (26, 'Charlie Chaplin Productions', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (27, 'Quad Productions', 'France');
INSERT INTO project.studio (studioid, name, country) VALUES (28, 'Castle Rock Entertainment', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (29, 'Orion-Nova Productions', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (30, 'Produzioni Europee Associati (PEA)', 'Italy');
INSERT INTO project.studio (studioid, name, country) VALUES (31, 'Fantasy Films', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (32, 'Toho Company', 'Japan');
INSERT INTO project.studio (studioid, name, country) VALUES (33, 'Liberty Films', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (34, 'PolyGram Filmed Entertainment', 'USA');
INSERT INTO project.studio (studioid, name, country) VALUES (35, 'Gaumont', 'France');
INSERT INTO project.studio (studioid, name, country) VALUES (36, 'Shamley Productions', 'USA');