INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (1, 'King', 'Stephen', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (2, 'Darabont', 'Frank', 'France');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (3, 'Puzo', 'Mario', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (4, 'Coppola', 'Francis Ford', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (5, 'Nolan', 'Jonathan', 'UK');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (6, 'Nolan', 'Christopher', 'UK');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (7, 'Keneally', 'Thomas', 'Australia');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (8, 'Zaillian', 'Steven', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (9, 'Rose', 'Reginald', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (10, 'Tarantino', 'Quentin', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (11, 'Avary', 'Roger', 'Canada');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (12, 'Walsh', 'Fran', 'New Zealand');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (13, 'Boyens', 'Philippa', 'New Zealand');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (14, 'Jackson', 'Peter', 'New Zealand');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (19, 'Palahniuk', 'Chuck ', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (20, 'Uhls', 'Jim', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (21, 'Brackett', 'Leigh', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (22, 'Kasdan', 'Lawrence', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (23, 'Lucas', 'George', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (24, 'Roth', 'Eric', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (25, 'Groom', 'Winston', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (26, 'Sinclair', 'Stephen', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (27, 'Hauben', 'Lawrence', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (28, 'Goldman', 'Bo', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (29, 'Kessey', 'Ken', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (30, 'Pileggi', 'Martin', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (31, 'Scorsese', 'Martin', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (32, 'Wachowski', 'Lilly', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (33, 'Wachowski', 'Lana', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (34, 'Kurosawa', 'Akira', 'Japan');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (35, 'Hashimoto', 'Shinobu', 'Japan');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (36, 'Oguni', 'Hideo', 'Japan');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (37, 'Lins', 'Paulo', 'Brazil');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (38, 'Mantovani', 'Braulio', 'Brazil');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (39, 'Walker', 'Andrew Kevin', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (40, 'Harris', 'Thomas', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (41, 'Tally', 'Ted', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (42, 'Goodrich', 'Frances', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (43, 'Hackett', 'Albert', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (44, 'Capra', 'Frank', 'Italy');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (45, 'Swerling', 'Jo', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (46, 'Van Doren Stern', 'Philip', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (47, 'McQuarrie', 'Christopher', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (48, 'Cerami', 'Vincenzo', 'Italy');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (49, 'Benigni', 'Roberto', 'Italy');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (50, 'Besson', 'Luc', 'France');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (51, 'Donati', 'Sergio', 'Italy');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (52, 'Miyazaki', 'Hayao', 'Japan');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (53, 'Rodat', 'Robert', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (54, 'Epstein ', 'Julius', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (55, 'Epstein', 'Philip', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (56, 'Koch', 'Howard', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (57, 'McKenna', 'David', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (58, 'Chapling', 'Charles', 'UK');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (59, 'Stefano', 'Joseph', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (60, 'Bloch', 'Robert', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (61, 'Kaufman', 'Philip', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (62, 'Hayes', 'John Michael', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (63, 'Woolrich', 'Cornell', 'USA');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (64, 'Nakache', 'Olivier', 'France');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (65, 'Toledano', 'Eric', 'France');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (15, 'Vincenzoni', 'Luciano', 'Italy');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (16, 'Leone', 'Sergio', 'Italy');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (17, 'Incrocci', 'Agenore', 'Italy');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (18, 'Scarpelli', 'Furio', 'Italy');
INSERT INTO project.writer (writerid, lastname, firstname, country) VALUES (66, 'Griffin', 'Ted', 'USA');